version: '3.1'

services:

  db:
    image: postgres
    networks:
      - djangonet
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  web:
    image: akiyoshi827/django
    networks:
      - djangonet
    volumes:
      - D:\develop\django\test:/code
    tty: true
    user: root
    depends_on:
      - db
    command: 
      bash -c "cd firstapp && uwsgi --http :8000 --module firstapp.wsgi"

  webserver:
    image: nginx
    networks:
      - djangonet
    volumes:
      - D:\develop\django\nginx\nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - web

volumes:
  postgres_db:

networks:
  djangonet: