version: '3.1'

services:

  python:
    image: jupyter/tensorflow-notebook
    volumes:
      - D:\develop\jupyter:/home/jovyan/work
    tty: true
    user: root
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    command: start-notebook.sh --NotebookApp.token=''