version: '3.1'

services:

  wordpress-db:
    image: mysql:5.7
    networks:
      - wordpressnet
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
    
  wordpress-app:
    depends_on: 
      - wordpress-db
    image: wordpress
    networks:
      - wordpressnet
    volumes:
      - wordpress:/var/www/html
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
    
networks:
  wordpressnet:

volumes:
  wordpress:
  db: